### ISSUE TITLE
Suggestion: Port the Mod To Minecraft 1.18.2

### ISSUE THREAD

**Issue by Talbe1** [Zensonaton/MinecraftClientGobrrr#5]
That's all I wanted to suggest.

**Comment by Zensonaton** [comment]
Got it. I will mention you here once I'm done :)

**Comment by Zensonaton** [comment]
Done! Currently, you can download MinecraftClientGobrrr for MC 1.18.2 (and 1.20) from [Github Releases page](https://github.com/Zensonaton/MinecraftClientGobrrr/releases/tag/1.1). I'll upload those to Modrinth and Curseforge a little bit later.

**UPD**: Published both to Modrinth and Curseforge.
